import React, { useState, useCallback, useRef } from 'react';
import {
  View,
  Text,
  TextInput,
  TouchableOpacity,
  ScrollView,
  StyleSheet,
  ActivityIndicator,
  Alert,
  Platform,
} from 'react-native';
import { LinearGradient } from 'expo-linear-gradient';
import { Ionicons } from '@expo/vector-icons';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { useDispatch, useSelector } from 'react-redux';
import * as DocumentPicker from 'expo-document-picker';
import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import { NativeStackNavigationProp } from '@react-navigation/native-stack';

import { brailleService } from '../../services';
import { printBrailleText } from '../../store/slices/deviceSlice';
import { RootState, AppDispatch } from '../../store';
import type { RootStackParamList } from '../../navigation/RootNavigator';

type Props = {
  navigation: NativeStackNavigationProp<RootStackParamList, 'BrailleConvert'>;
};

const C = {
  bg:        '#0A0A0F',
  card:      '#1E293B',
  cardDark:  '#0F172A',
  blue:      '#3B82F6',
  blueDark:  '#2563EB',
  green:     '#10B981',
  greenDk:   '#059669',
  purple:    '#8B5CF6',
  purpleDk:  '#7C3AED',
  orange:    '#F59E0B',
  white:     '#FFFFFF',
  dim:       'rgba(255,255,255,0.55)',
  border:    'rgba(255,255,255,0.12)',
};

// ── Document text extraction ──────────────────────────────────────────────────

async function extractTextFromFile(
  uri: string,
  mimeType: string,
  name: string,
): Promise<string> {
  const ext = name.split('.').pop()?.toLowerCase() ?? '';

  if (ext === 'txt' || mimeType === 'text/plain') {
    const response = await fetch(uri);
    return await response.text();
  }

  if (ext === 'docx' ||
      mimeType === 'application/vnd.openxmlformats-officedocument.wordprocessingml.document') {
    const response = await fetch(uri);
    const arrayBuffer = await response.arrayBuffer();
    const mammoth = require('mammoth');
    const result = await mammoth.extractRawText({ arrayBuffer });
    return result.value;
  }

  throw new Error(
    `Unsupported file type: .${ext}\nSupported formats: .txt, .docx`,
  );
}

// ── Build PDF HTML for export ─────────────────────────────────────────────────

function buildPdfHtml(originalText: string, brailleText: string): string {
  const safeOrig   = originalText.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
  const safeBraille = brailleText.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

  return `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8"/>
<style>
  body { font-family: Arial, sans-serif; margin: 40px; color: #1a1a1a; }
  h1   { font-size: 22px; color: #1D4ED8; margin-bottom: 4px; }
  h2   { font-size: 16px; color: #374151; margin-top: 28px; margin-bottom: 8px; }
  pre  { font-size: 13px; line-height: 1.7; white-space: pre-wrap; word-break: break-word;
         background: #F9FAFB; padding: 16px; border-radius: 8px; border: 1px solid #E5E7EB; }
  .braille { font-size: 22px; line-height: 2; letter-spacing: 4px; }
  footer { margin-top: 40px; font-size: 11px; color: #9CA3AF; }
</style>
</head>
<body>
<h1>Braille Conversion Report</h1>
<p style="font-size:12px;color:#6B7280;">Generated by BrailleTutor App</p>

<h2>Original Text</h2>
<pre>${safeOrig}</pre>

<h2>Braille Output (Grade 1 Unicode)</h2>
<pre class="braille">${safeBraille}</pre>

<footer>Grade 1 Braille • BrailleTutor © ${new Date().getFullYear()}</footer>
</body>
</html>`;
}

// ── Component ─────────────────────────────────────────────────────────────────

export const BrailleConvertScreen: React.FC<Props> = ({ navigation }) => {
  const safeInsets  = useSafeAreaInsets();
  const appDispatch = useDispatch<AppDispatch>();
  const deviceConnected = useSelector((s: RootState) => (s as any).device?.connected ?? false);

  const [inputText, setInputText]         = useState('');
  const [brailleOutput, setBrailleOutput] = useState('');
  const [brailleCells, setBrailleCells]   = useState<any[]>([]);
  const [converting, setConverting]       = useState(false);
  const [uploading, setUploading]         = useState(false);
  const [printing, setPrinting]           = useState(false);
  const [exporting, setExporting]         = useState(false);
  const [fileName, setFileName]           = useState<string | null>(null);
  const [charCount, setCharCount]         = useState(0);

  const scrollRef = useRef<ScrollView>(null);

  // ── Text conversion ─────────────────────────────────────────────────────────

  const handleConvert = useCallback(() => {
    if (!inputText.trim()) {
      Alert.alert('No Text', 'Please enter or upload text to convert.');
      return;
    }
    setConverting(true);
    try {
      const result = brailleService.textToBraille(inputText);
      setBrailleOutput(result.brailleUnicode);
      setBrailleCells(result.cells);
      setCharCount(result.cells.length);
      setTimeout(() => scrollRef.current?.scrollToEnd({ animated: true }), 300);
    } finally {
      setConverting(false);
    }
  }, [inputText]);

  // ── Document upload ─────────────────────────────────────────────────────────

  const handleUpload = useCallback(async () => {
    setUploading(true);
    try {
      const result = await DocumentPicker.getDocumentAsync({
        type: [
          'text/plain',
          'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
        ],
        copyToCacheDirectory: true,
      });

      if (result.canceled) return;

      const file = result.assets[0];
      const text = await extractTextFromFile(file.uri, file.mimeType ?? '', file.name ?? '');
      setInputText(text);
      setFileName(file.name ?? 'document');
      setBrailleOutput('');
      setBrailleCells([]);
    } catch (err) {
      Alert.alert('Upload Failed', (err as Error).message);
    } finally {
      setUploading(false);
    }
  }, []);

  // ── Print via BLE device ────────────────────────────────────────────────────

  const handlePrint = useCallback(async () => {
    if (!brailleOutput) {
      Alert.alert('Nothing to Print', 'Convert text to Braille first.');
      return;
    }
    if (!deviceConnected) {
      Alert.alert('No Device', 'Connect a Braille device first from the Device tab.');
      return;
    }
    setPrinting(true);
    try {
      await appDispatch(printBrailleText(inputText));
      Alert.alert('Print Started', 'Your Braille document is being printed.');
    } catch (err) {
      Alert.alert('Print Failed', (err as Error).message);
    } finally {
      setPrinting(false);
    }
  }, [brailleOutput, inputText, deviceConnected, appDispatch]);

  // ── Export as PDF ───────────────────────────────────────────────────────────

  const handleExportPDF = useCallback(async () => {
    if (!brailleOutput) {
      Alert.alert('Nothing to Export', 'Convert text to Braille first.');
      return;
    }
    setExporting(true);
    try {
      const html = buildPdfHtml(inputText, brailleOutput);
      const { uri } = await Print.printToFileAsync({ html, base64: false });

      const canShare = await Sharing.isAvailableAsync();
      if (canShare) {
        await Sharing.shareAsync(uri, {
          mimeType: 'application/pdf',
          dialogTitle: 'Save Braille PDF',
        });
      } else {
        Alert.alert('PDF Saved', `Saved to: ${uri}`);
      }
    } catch (err) {
      Alert.alert('Export Failed', (err as Error).message);
    } finally {
      setExporting(false);
    }
  }, [brailleOutput, inputText]);

  // ── Print preview via system dialog ────────────────────────────────────────

  const handleSystemPrint = useCallback(async () => {
    if (!brailleOutput) {
      Alert.alert('Nothing to Print', 'Convert text to Braille first.');
      return;
    }
    const html = buildPdfHtml(inputText, brailleOutput);
    await Print.printAsync({ html });
  }, [brailleOutput, inputText]);

  // ── Render ───────────────────────────────────────────────────────────────────

  return (
    <View style={styles.root}>
      <LinearGradient
        colors={[C.cardDark, C.bg]}
        style={StyleSheet.absoluteFill}
      />

      {/* Header */}
      <LinearGradient
        colors={[C.card, C.cardDark]}
        style={[styles.header, { paddingTop: safeInsets.top + 14 }]}
      >
        <TouchableOpacity onPress={() => navigation.goBack()} style={styles.backBtn}>
          <Ionicons name="chevron-back" size={22} color={C.white} />
        </TouchableOpacity>
        <View style={styles.headerCenter}>
          <Text style={styles.headerTitle}>Braille Converter</Text>
          <Text style={styles.headerSub}>Grade 1 • 100% accurate</Text>
        </View>
        <View style={{ width: 36 }} />
      </LinearGradient>

      <ScrollView
        ref={scrollRef}
        style={styles.scroll}
        contentContainerStyle={styles.scrollContent}
        keyboardShouldPersistTaps="handled"
        showsVerticalScrollIndicator={false}
      >
        {/* ── Upload section ────────────────────────────────────────────── */}
        <View style={styles.section}>
          <Text style={styles.sectionLabel}>1. Add Text</Text>
          <TouchableOpacity
            style={styles.uploadBtn}
            onPress={handleUpload}
            disabled={uploading}
            activeOpacity={0.8}
          >
            <LinearGradient
              colors={[C.blue, C.blueDark]}
              style={styles.uploadGrad}
              start={{ x: 0, y: 0 }}
              end={{ x: 1, y: 1 }}
            >
              {uploading ? (
                <ActivityIndicator color={C.white} />
              ) : (
                <>
                  <Ionicons name="cloud-upload-outline" size={24} color={C.white} />
                  <Text style={styles.uploadText}>
                    {fileName ? `Uploaded: ${fileName}` : 'Upload .docx or .txt'}
                  </Text>
                </>
              )}
            </LinearGradient>
          </TouchableOpacity>

          <Text style={styles.orLabel}>— or type below —</Text>

          <TextInput
            style={styles.textInput}
            multiline
            numberOfLines={6}
            placeholder="Type or paste text here…"
            placeholderTextColor="rgba(255,255,255,0.3)"
            value={inputText}
            onChangeText={text => {
              setInputText(text);
              setBrailleOutput('');
              setBrailleCells([]);
              if (text !== inputText) setFileName(null);
            }}
            textAlignVertical="top"
            autoCapitalize="none"
            autoCorrect={false}
          />
          {inputText.length > 0 && (
            <Text style={styles.charHint}>{inputText.length} characters</Text>
          )}
        </View>

        {/* ── Convert button ─────────────────────────────────────────────── */}
        <TouchableOpacity
          style={styles.convertBtn}
          onPress={handleConvert}
          disabled={converting || !inputText.trim()}
          activeOpacity={0.85}
        >
          <LinearGradient
            colors={[C.purple, C.purpleDk]}
            style={styles.convertGrad}
            start={{ x: 0, y: 0 }}
            end={{ x: 1, y: 1 }}
          >
            {converting ? (
              <ActivityIndicator color={C.white} />
            ) : (
              <>
                <Ionicons name="swap-horizontal" size={20} color={C.white} />
                <Text style={styles.convertText}>Convert to Braille</Text>
              </>
            )}
          </LinearGradient>
        </TouchableOpacity>

        {/* ── Braille output ─────────────────────────────────────────────── */}
        {brailleOutput.length > 0 && (
          <>
            <View style={styles.section}>
              <View style={styles.outputHeader}>
                <Text style={styles.sectionLabel}>2. Braille Output</Text>
                <View style={styles.badge}>
                  <Text style={styles.badgeText}>{charCount} cells</Text>
                </View>
              </View>

              <View style={styles.brailleCard}>
                <Text style={styles.brailleText} selectable>
                  {brailleOutput}
                </Text>
              </View>

              {/* Cell-by-cell preview (first 50 cells) */}
              <Text style={styles.cellPreviewLabel}>Cell detail (first 50)</Text>
              <ScrollView
                horizontal
                showsHorizontalScrollIndicator={false}
                style={styles.cellRow}
              >
                {brailleCells.slice(0, 50).map((cell, i) => (
                  <View key={i} style={styles.cellCard}>
                    <Text style={styles.cellUnicode}>{cell.unicode}</Text>
                    <Text style={styles.cellChar}>
                      {cell.character === ' ' ? '⎵' : cell.character}
                    </Text>
                    <View style={styles.dotGrid}>
                      {[0, 1, 2].map(row => (
                        <View key={row} style={styles.dotRow}>
                          {[0, 1].map(col => {
                            const dotNum = row + 1 + (col === 1 ? 3 : 0);
                            const active = cell.dots.includes(dotNum);
                            return (
                              <View
                                key={col}
                                style={[styles.dot, active && styles.dotActive]}
                              />
                            );
                          })}
                        </View>
                      ))}
                    </View>
                  </View>
                ))}
              </ScrollView>
            </View>

            {/* ── Action buttons ──────────────────────────────────────────── */}
            <View style={styles.actionsSection}>
              <Text style={styles.sectionLabel}>3. Actions</Text>

              <View style={styles.actionsGrid}>
                {/* Export PDF */}
                <TouchableOpacity
                  style={styles.actionCard}
                  onPress={handleExportPDF}
                  disabled={exporting}
                  activeOpacity={0.8}
                >
                  <LinearGradient
                    colors={['rgba(16,185,129,0.25)', 'rgba(5,150,105,0.15)']}
                    style={styles.actionGrad}
                  >
                    {exporting ? (
                      <ActivityIndicator color={C.green} />
                    ) : (
                      <Ionicons name="document-text" size={28} color={C.green} />
                    )}
                    <Text style={[styles.actionTitle, { color: C.green }]}>Export PDF</Text>
                    <Text style={styles.actionSub}>Save & share</Text>
                  </LinearGradient>
                </TouchableOpacity>

                {/* System Print */}
                <TouchableOpacity
                  style={styles.actionCard}
                  onPress={handleSystemPrint}
                  activeOpacity={0.8}
                >
                  <LinearGradient
                    colors={['rgba(59,130,246,0.25)', 'rgba(37,99,235,0.15)']}
                    style={styles.actionGrad}
                  >
                    <Ionicons name="print" size={28} color={C.blue} />
                    <Text style={[styles.actionTitle, { color: C.blue }]}>Print</Text>
                    <Text style={styles.actionSub}>System printer</Text>
                  </LinearGradient>
                </TouchableOpacity>

                {/* BLE Device Print */}
                <TouchableOpacity
                  style={[styles.actionCard, !deviceConnected && styles.actionDisabled]}
                  onPress={handlePrint}
                  disabled={printing || !deviceConnected}
                  activeOpacity={0.8}
                >
                  <LinearGradient
                    colors={['rgba(139,92,246,0.25)', 'rgba(109,40,217,0.15)']}
                    style={styles.actionGrad}
                  >
                    {printing ? (
                      <ActivityIndicator color={C.purple} />
                    ) : (
                      <Ionicons name="bluetooth" size={28} color={C.purple} />
                    )}
                    <Text style={[styles.actionTitle, { color: C.purple }]}>
                      Braille Device
                    </Text>
                    <Text style={styles.actionSub}>
                      {deviceConnected ? 'Print via BLE' : 'Device not connected'}
                    </Text>
                  </LinearGradient>
                </TouchableOpacity>

                {/* Clear */}
                <TouchableOpacity
                  style={styles.actionCard}
                  onPress={() => {
                    setInputText('');
                    setBrailleOutput('');
                    setBrailleCells([]);
                    setFileName(null);
                  }}
                  activeOpacity={0.8}
                >
                  <LinearGradient
                    colors={['rgba(245,158,11,0.25)', 'rgba(217,119,6,0.15)']}
                    style={styles.actionGrad}
                  >
                    <Ionicons name="trash-outline" size={28} color={C.orange} />
                    <Text style={[styles.actionTitle, { color: C.orange }]}>Clear</Text>
                    <Text style={styles.actionSub}>Start over</Text>
                  </LinearGradient>
                </TouchableOpacity>
              </View>
            </View>
          </>
        )}

        {/* Bottom padding */}
        <View style={{ height: 60 }} />
      </ScrollView>
    </View>
  );
};

// ── Styles ────────────────────────────────────────────────────────────────────

const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: C.bg,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingBottom: 16,
  },
  backBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: 'rgba(255,255,255,0.1)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerCenter: {
    flex: 1,
    alignItems: 'center',
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: C.white,
  },
  headerSub: {
    fontSize: 12,
    color: C.dim,
    marginTop: 2,
  },

  scroll: { flex: 1 },
  scrollContent: { padding: 16, paddingTop: 20 },

  section: { marginBottom: 20 },
  sectionLabel: {
    fontSize: 14,
    fontWeight: '700',
    color: C.dim,
    letterSpacing: 0.5,
    marginBottom: 10,
    textTransform: 'uppercase',
  },

  uploadBtn: {
    borderRadius: 14,
    overflow: 'hidden',
    marginBottom: 12,
    borderWidth: 1,
    borderColor: 'rgba(59,130,246,0.35)',
  },
  uploadGrad: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 14,
    gap: 10,
  },
  uploadText: {
    fontSize: 15,
    fontWeight: '600',
    color: C.white,
  },

  orLabel: {
    textAlign: 'center',
    color: 'rgba(255,255,255,0.3)',
    fontSize: 12,
    marginBottom: 10,
    letterSpacing: 0.5,
  },

  textInput: {
    backgroundColor: C.card,
    borderWidth: 1,
    borderColor: C.border,
    borderRadius: 14,
    padding: 14,
    color: C.white,
    fontSize: 14,
    lineHeight: 20,
    minHeight: 120,
  },
  charHint: {
    fontSize: 11,
    color: 'rgba(255,255,255,0.3)',
    textAlign: 'right',
    marginTop: 4,
  },

  convertBtn: {
    borderRadius: 14,
    overflow: 'hidden',
    marginBottom: 20,
    borderWidth: 1,
    borderColor: 'rgba(139,92,246,0.4)',
  },
  convertGrad: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 15,
    gap: 10,
  },
  convertText: {
    fontSize: 16,
    fontWeight: '700',
    color: C.white,
  },

  outputHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  badge: {
    backgroundColor: 'rgba(139,92,246,0.25)',
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 3,
  },
  badgeText: {
    fontSize: 12,
    fontWeight: '600',
    color: C.purple,
  },

  brailleCard: {
    backgroundColor: C.card,
    borderRadius: 14,
    padding: 16,
    borderWidth: 1,
    borderColor: C.border,
    marginBottom: 12,
  },
  brailleText: {
    fontSize: 26,
    lineHeight: 38,
    letterSpacing: 4,
    color: C.white,
    fontWeight: '400',
  },

  cellPreviewLabel: {
    fontSize: 11,
    color: 'rgba(255,255,255,0.35)',
    marginBottom: 8,
    letterSpacing: 0.3,
  },
  cellRow: { marginBottom: 4 },
  cellCard: {
    backgroundColor: C.card,
    borderRadius: 10,
    padding: 8,
    marginRight: 8,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: C.border,
    minWidth: 48,
  },
  cellUnicode: { fontSize: 20, color: C.white, marginBottom: 2 },
  cellChar: { fontSize: 10, color: C.dim, marginBottom: 4 },
  dotGrid: { gap: 3 },
  dotRow: { flexDirection: 'row', gap: 3 },
  dot: {
    width: 8, height: 8, borderRadius: 4,
    backgroundColor: 'rgba(255,255,255,0.15)',
  },
  dotActive: { backgroundColor: C.blue },

  actionsSection: { marginBottom: 8 },
  actionsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  actionCard: {
    width: '47%',
    borderRadius: 14,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: C.border,
  },
  actionDisabled: { opacity: 0.45 },
  actionGrad: {
    alignItems: 'center',
    justifyContent: 'center',
    padding: 16,
    minHeight: 110,
  },
  actionTitle: {
    fontSize: 14,
    fontWeight: '700',
    marginTop: 8,
  },
  actionSub: {
    fontSize: 11,
    color: 'rgba(255,255,255,0.45)',
    marginTop: 2,
  },
});

export default BrailleConvertScreen;
